- name: Pre-Run // Group Host
  hosts: localhost
  tasks:
    - name: Pre-Run // Setup Default Group
      add_host:
        name: "{{ ansible_hostname }}"
        groups: default
      changed_when: False

    - name: Pre-Run // Setup Display Group
      add_host:
        name: "{{ ansible_hostname }}"
        groups: display
      when: ansible_facts['env']['DISPLAY'] is defined
      changed_when: False

    - name: Pre-Run // Setup MRT Group
      add_host:
        name: "{{ ansible_hostname }}"
        groups: mrt
      when: "'mrt' in ansible_hostname"
      changed_when: False

- hosts: default
  become: true
  tags: [never, privileged]
  pre_tasks:
    - name: Pre-Run // Update pacman cache
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: Pre-Run // Update apt cache
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: default
  roles:
    - default

- hosts: display
  roles:
    - display

- hosts: mrt
  roles:
    - mrt

