- name: Pre-Run // Group Host
  hosts: localhost
  tasks:
    - name: Pre-Run // Setup All Group
      add_host:
        name: "{{ ansible_hostname }}"
        groups: all

    - name: Pre-Run // Setup MRT Group
      add_host:
        name: "{{ ansible_hostname }}"
        groups: mrt
      when: "'mrt' in ansible_hostname"

- hosts: privileged
  become: true
  pre_tasks:
    - name: Pre-Run // Update Package Cache
      apt: update_cache=yes
      changed_when: False

- hosts: privileged
  become: true
  roles:
    - privileged

- hosts: all
  roles:
    - user_config

- hosts: mrt
  roles:
    - mrt

