- hosts: local
  become: true
  tags: [never, privileged]
  pre_tasks:
    - name: Pre-Run // Update pacman cache
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: Pre-Run // Update apt cache
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Full setup
  hosts: local
  pre_tasks:
    - tags: always
      block:
        - name: Check if host has a display
          set_fact:
            has_display: >-
              {{
                (ansible_facts['env']['DISPLAY'] is defined
                 and ansible_facts['env']['DISPLAY'] is match('^:[0-9]'))
                or
                (ansible_facts['env']['WAYLAND_DISPLAY'] is defined
                 and ansible_facts['env']['WAYLAND_DISPLAY'] | length > 0)
              }}
        - debug:
            msg: >-
              {{
                "Host has a display" if has_display
                else "Host does not have a display"
              }}

        - name: Check GitHub SSH access
          ansible.builtin.command: ssh -T git@github.com
          register: github_ssh_test
          failed_when: false
          changed_when: false
        - name: Set GitHub prefix
          set_fact:
            github_prefix: >-
              {{
                "git@github.com:"
                if github_ssh_test.rc in [0, 1]
                else "https://github.com/"
              }}
        - debug:
            msg: "GitHub prefix set to {{ github_prefix }}"


  roles:
    - role: mise
      tags: mise

    - role: bash
      tags: bash
    - role: nushell
      tags: nushell

    - role: bat
      tags: bat
    - role: eza
      tags: eza
    - role: fd
      tags: fd
    - role: fzf
      tags: fzf
    - role: git
      tags: git
    - role: lazygit
      tags: lazygit
    - role: leadr
      tags: leadr
    - role: locale
      tags: locale
    - role: neovim
      tags: neovim
    - role: nodejs
      tags: nodejs
    - role: ripgrep
      tags: ripgrep
    - role: starship
      tags: starship
    - role: tmux
      tags: tmux
    - role: update
      tags: update
    - role: uv
      tags: uv
    - role: xdg_open
      tags: xdg_open
    - role: zoxide
      tags: zoxide

    - role: gnome
      when: has_display
      tags: gnome
    - role: kitty
      when: has_display
      tags: kitty
    - role: nerdfont
      when: has_display
      tags: nerdfont

    - role: mrt
      when: "'mrt' in ansible_facts['hostname']"
      tags: mrt
