- name: Pre-Run // Group Host
  hosts: localhost
  tasks:
    - name: Pre-Run // Setup Default Group
      add_host:
        name: "{{ ansible_hostname }}"
        groups: default
      changed_when: False

    - name: Pre-Run // Setup MRT Group
      add_host:
        name: "{{ ansible_hostname }}"
        groups: mrt
      when: "'mrt' in ansible_hostname"
      changed_when: False

- hosts: default
  become: true
  pre_tasks:
    - name: Pre-Run // Update Package Cache
      apt: update_cache=yes
      changed_when: False
  tags: [never, privileged]

- hosts: privileged
  become: true
  roles:
    - privileged

- hosts: default
  roles:
    - user_config

- hosts: mrt
  roles:
    - mrt

