- name: Install
  ansible.builtin.shell: |
    {{ ansible_env.HOME }}/.local/bin/mise use --global lazygit
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/mise/installs/lazygit"

- name: Add bash config
  ansible.builtin.copy:
    src: lazygit.bash
    dest: "{{ ansible_env.HOME }}/.config/bash/lazygit.bash"

- name: Ensure config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/lazygit"
    state: directory

- name: Add lazygit config
  ansible.builtin.copy:
    src: config.yml
    dest: "{{ ansible_env.HOME }}/.config/lazygit/config.yml"

