- name: Neovim // Download Appimage
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/v0.9.5/nvim.appimage"
    dest: "{{ ansible_env.HOME }}/.local/bin/nvim"
    checksum: sha256:0c82e5702af7a11fbb916a11b4a82e98928abf8266c74b2030ea740340437bf9
    mode: "0755"

- name: Neovim // Clone Config
  ansible.builtin.git:
    repo: "https://github.com/ll-nick/neovim-config.git"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    force: "true"

