- name: MRT // Add bash config
  ansible.builtin.copy:
    src: bash/mrt.bash
    dest: "{{ ansible_env.HOME }}/.config/bash/mrt.bash"

- name: MRT // Check if mrt tools are installed
  ansible.builtin.stat:
    path: /opt/mrtsoftware
  register: mrtsoftware_dir

- name: MRT // ROS configuration
  when: mrtsoftware_dir.stat.exists
  block:
    - name: MRT // Clone rossrc
      ansible.builtin.git:
        repo: "https://github.com/ll-nick/rossrc.git"
        dest: "{{ ansible_env.HOME }}/.rossrc"
        force: "true"

    - name: MRT // Add mrtros bash config
      when: mrtsoftware_dir.stat.exists
      ansible.builtin.copy:
        src: bash/mrtros.bash
        dest: "{{ ansible_env.HOME }}/.config/bash/mrtros.bash"
