- name: Add bash config
  ansible.builtin.copy:
    src: mrt.bash
    dest: "{{ ansible_env.HOME }}/.config/bash/mrt.bash"

- name: Check if mrt tools are installed
  ansible.builtin.stat:
    path: /opt/mrtsoftware
  register: mrtsoftware_dir

- name: ROS configuration
  when: mrtsoftware_dir.stat.exists
  block:
    - name: Clone rossrc
      ansible.builtin.git:
        repo: "{{ github_prefix }}ll-nick/rossrc.git"
        dest: "{{ ansible_env.HOME }}/.rossrc"
        force: "true"

    - name: Add mrtros bash config
      ansible.builtin.copy:
        src: mrtros.bash
        dest: "{{ ansible_env.HOME }}/.config/bash/mrtros.bash"
