- name: tmux // Download binary
  ansible.builtin.get_url:
    url: "https://github.com/pythops/tmux-linux-binary/releases/download/v{{ tmux_version }}/tmux-linux-x86_64"
    dest: "{{ ansible_env.HOME }}/.local/bin/tmux"
    mode: "0755"
  when: ansible_architecture == "x86_64"

