- name: Install
  ansible.builtin.shell: |
    MISE_NODE_COMPILE=false {{ ansible_env.HOME }}/.local/bin/mise use --global node
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/mise/installs/node"

