- name: Copy mise config
  ansible.builtin.copy:
    src: mise.toml
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/mise/conf.d/nodejs.toml"

- name: Install
  ansible.builtin.command:
    cmd: "{{ ansible_facts['env']['HOME'] }}/.local/bin/mise install"
  changed_when: false

