- name: Copy mise config
  ansible.builtin.copy:
    src: mise.toml
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/mise/conf.d/nushell.toml"

- name: Install
  ansible.builtin.command:
    cmd: "{{ ansible_facts['env']['HOME'] }}/.local/bin/mise install"
  changed_when: false

- name: Clone config
  ansible.builtin.git:
    repo: "{{ github_prefix }}ll-nick/nushell-config"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/nushell"
  ignore_errors: true

- name: Ensure autoload directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.local/share/nushell/vendor/autoload"
    state: directory

- name: Generate carapace init script
  ansible.builtin.command:
    cmd: mise exec -- carapace _carapace nushell
  register: carapace_init
  changed_when: false

- name: Write carapace init file
  ansible.builtin.copy:
    dest: "{{ ansible_facts['env']['HOME'] }}/.local/share/nushell/vendor/autoload/carapace.nu"
    content: "{{ carapace_init.stdout }}"
    mode: "0644"

- name: Generate mise init script
  ansible.builtin.command:
    cmd: mise activate nu
  register: mise_init
  changed_when: false

- name: Write mise init file
  ansible.builtin.copy:
    dest: "{{ ansible_facts['env']['HOME'] }}/.local/share/nushell/vendor/autoload/00_mise.nu"
    content: "{{ mise_init.stdout }}"
    mode: "0644"
