- name: Copy mise config
  ansible.builtin.copy:
    src: mise.toml
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/mise/conf.d/zoxide.toml"

- name: Install
  ansible.builtin.command:
    cmd: "{{ ansible_facts['env']['HOME'] }}/.local/bin/mise install"
  changed_when: false

- name: Add bash config
  ansible.builtin.copy:
    src: zoxide.bash
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/bash/zoxide.bash"

- name: Generate nushell init script
  ansible.builtin.command:
    cmd: mise exec -- zoxide init --cmd cd nushell
  register: zoxide_init
  changed_when: false

- name: Write nushell init file
  ansible.builtin.copy:
    dest: "{{ ansible_facts['env']['HOME'] }}/.local/share/nushell/vendor/autoload/zoxide.nu"
    content: "{{ zoxide_init.stdout }}"
    mode: "0644"
