- block:
  - import_tasks: subtasks/bash.yml
  - import_tasks: subtasks/fzf.yml
  - import_tasks: subtasks/lazygit.yml
  - import_tasks: subtasks/leadr.yml
  - import_tasks: subtasks/locale.yml
  - import_tasks: subtasks/nerdfont.yml
  - import_tasks: subtasks/nodejs.yml
  - import_tasks: subtasks/pipx.yml
  - import_tasks: subtasks/starship.yml
  - import_tasks: subtasks/thefuck.yml
  - import_tasks: subtasks/tmux/main.yml
  - import_tasks: subtasks/update.yml
  - import_tasks: subtasks/z.yml

