- name: Check if kitty exists in system PATH
  ansible.builtin.command: "command -v kitty"
  register: kitty_system_check
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Check if kitty exists in user local/bin
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/bin/kitty"
  register: kitty_local_check
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Determine if kitty is installed
  set_fact:
    kitty_installed: "{{ kitty_system_check.rc == 0 or kitty_local_check.stat.exists }}"

- name: Install kitty
  become: true
  tags: [never, privileged]
  ansible.builtin.package:
    name: kitty
    state: present
  when:
    - not kitty_installed
    - ansible_distribution == "Archlinux"

- name: Install kitty manually
  ansible.builtin.include_tasks: install.yml
  when:
    - not kitty_installed
    - ansible_distribution != "Archlinux"
    - ansible_distribution != "NixOS"

- name: Clone Config
  ansible.builtin.git:
    repo: "{{ github_prefix }}ll-nick/kitty-config.git"
    dest: "{{ ansible_env.HOME }}/.config/kitty"
    force: "true"

