- name: Install
  ansible.builtin.shell: |
    {{ ansible_env.HOME }}/.local/bin/mise use --global github:kovidgoyal/kitty
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/mise/installs/github-kovidgoyal-kitty"
  register: kitty_install
  # kitty is best installed via nixpkgs on NixOS
  when: ansible_distribution != "NixOS"

- name: Post-install tasks
  when: kitty_install.changed and ansible_distribution != "NixOS"
  block:
  - name: Copy kitty.desktop to appropriate location
    ansible.builtin.copy:
      src: "{{ ansible_env.HOME }}/.local/share/mise/installs/github-kovidgoyal-kitty/latest/share/applications/kitty.desktop"
      dest: "{{ ansible_env.HOME }}/.local/share/applications/kitty.desktop"

  - name: Copy kitty-open.desktop to appropriate location
    ansible.builtin.copy:
      src: "{{ ansible_env.HOME }}/.local/share/mise/installs/github-kovidgoyal-kitty/latest/share/applications/kitty-open.desktop"
      dest: "{{ ansible_env.HOME }}/.local/share/applications/kitty-open.desktop"

  - name: Update Icon path in .desktop files
    ansible.builtin.shell:
      cmd: "sed -i 's|Icon=kitty|Icon={{ ansible_env.HOME }}/.local/share/mise/installs/github-kovidgoyal-kitty/latest/share/icons/hicolor/256x256/apps/kitty.png|g' ~/.local/share/applications/kitty*.desktop"
    args:
      executable: /bin/bash

  - name: Update Exec path in .desktop files
    ansible.builtin.shell:
      cmd: "sed -i 's|Exec=kitty|Exec={{ ansible_env.HOME }}/.local/share/mise/installs/github-kovidgoyal-kitty/latest/bin/kitty|g' ~/.local/share/applications/kitty*.desktop"
    args:
      executable: /bin/bash

  - name: Make xdg-terminal-exec use kitty
    ansible.builtin.lineinfile:
      path: "{{ ansible_env.HOME }}/.config/xdg-terminals.list"
      line: 'kitty.desktop'
      create: yes

- name: Clone Config
  ansible.builtin.git:
    repo: "{{ github_prefix }}ll-nick/kitty-config.git"
    dest: "{{ ansible_env.HOME }}/.config/kitty"
    force: "true"

