- name: Install psutil
  ansible.builtin.pip:
    name: psutil
    state: latest
    executable: "{{ ansible_env.HOME }}/.local/share/mise/shims/pip"

# Dark Mode
- name: Enable Dark Mode
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

# Cursor Theme
- name: Ensure icons Directory at .icons
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.icons"
    state: directory
- name: Download Cursor Theme to .icons
  ansible.builtin.unarchive:
    src: https://github.com/catppuccin/cursors/releases/download/v2.0.0/catppuccin-mocha-blue-cursors.zip
    dest: "{{ ansible_env.HOME }}/.icons/"
    remote_src: yes
    creates: "{{ ansible_env.HOME }}/.icons/catppuccin-mocha-blue-cursors"

  # It appears that some applications only respect the cursor theme in .local/share/icons while others only respect it in .icons
  # So we'll copy the theme to both locations to ensure it works everywhere
- name: Ensure icons Directory at .local/share/icons
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/icons"
    state: directory
- name: Download Cursor Theme to .local/share/icons
  ansible.builtin.unarchive:
    src: https://github.com/catppuccin/cursors/releases/download/v2.0.0/catppuccin-mocha-blue-cursors.zip
    dest: "{{ ansible_env.HOME }}/.local/share/icons/"
    remote_src: yes
    creates: "{{ ansible_env.HOME }}/.local/share/icons/catppuccin-mocha-blue-cursors"

- name: Set Icon Theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/cursor-theme"
    value: "'catppuccin-mocha-blue-cursors'"

# Wallpaper
- name: Set Dark Mode Wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'https://github.com/ll-nick/ansible-config/blob/main/roles/gnome/files/wallpaper-dark.png?raw=true'"

- name: Set Light Mode Wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'https://github.com/ll-nick/ansible-config/blob/main/roles/gnome/files/wallpaper-light.png?raw=true'"

