- name: Install psutil
  ansible.builtin.pip:
    name: psutil
    state: present
    executable: python

- name: Ensure icons Directory at .icons
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.icons"
    state: directory
- name: Download Cursor Theme to .icons
  ansible.builtin.unarchive:
    src: https://github.com/catppuccin/cursors/releases/download/v2.0.0/catppuccin-mocha-blue-cursors.zip
    dest: "{{ ansible_env.HOME }}/.icons/"
    remote_src: yes
    creates: "{{ ansible_env.HOME }}/.icons/catppuccin-mocha-blue-cursors"

  # It appears that some applications only respect the cursor theme in .local/share/icons while others only respect it in .icons
  # So we'll copy the theme to both locations to ensure it works everywhere
- name: Ensure icons Directory at .local/share/icons
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/icons"
    state: directory
- name: Download Cursor Theme to .local/share/icons
  ansible.builtin.unarchive:
    src: https://github.com/catppuccin/cursors/releases/download/v2.0.0/catppuccin-mocha-blue-cursors.zip
    dest: "{{ ansible_env.HOME }}/.local/share/icons/"
    remote_src: yes
    creates: "{{ ansible_env.HOME }}/.local/share/icons/catppuccin-mocha-blue-cursors"

- name: Set Icon Theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/cursor-theme"
    value: "'catppuccin-mocha-blue-cursors'"

- name: Ensure Picture Directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/misc/xdg-directories/pictures"
    state: directory

- name: Download Wallpaper
  ansible.builtin.get_url:
    url: "https://github.com/zhichaoh/catppuccin-wallpapers/blob/main/landscapes/shaded_landscape.png?raw=true"
    dest: "{{ ansible_env.HOME }}/misc/xdg-directories/pictures/wallpaper.png"
    checksum: sha256:1199a43751f1234d3fb92ecf614fbf34de2c07334d3fdd355891044f51bddada

- name: Set Wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///{{ ansible_env.HOME }}/misc/xdg-directories/pictures/wallpaper.png'"

