- name: Copy mise config
  ansible.builtin.copy:
    src: mise.toml
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/mise/conf.d/fzf.toml"

- name: Install
  ansible.builtin.command:
    cmd: "{{ ansible_facts['env']['HOME'] }}/.local/bin/mise install"
  changed_when: false

- name: Add bash config
  ansible.builtin.copy:
    src: fzf.bash
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/bash/fzf.bash"

- name: Add nushell config
  ansible.builtin.copy:
    src: fzf.nu
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/nushell/autoload/fzf.nu"

