- name: lazygit // Ensure Directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

- name: lazygit // Check installed version
  command: lazygit --version | grep -o ', version=[^,]*' | awk -F= '{print $2}'
  ignore_errors: true
  changed_when: false
  failed_when: false
  register: lazygit_installed_version

- when: lazygit_installed_version.rc != 0 or lazygit_installed_version.stdout is version(lazygit_version, "!=")
  block:
    - name: lazygit // Install
      ansible.builtin.unarchive:
        src: "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz"
        dest: "{{ ansible_env.HOME }}/.local/bin/"
        remote_src: yes
      when: ansible_architecture == "x86_64"

    - name: lazygit // Install
      ansible.builtin.unarchive:
        src: "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_Linux_arm64.tar.gz"
        dest: "{{ ansible_env.HOME }}/.local/bin/"
        remote_src: yes
      when: ansible_architecture == "aarch64"

