- name: pipx // Create virtual environment for pipx
  ansible.builtin.command:
    cmd: python3 -m venv ~/.local/venvs/pipx
    creates: "{{ ansible_env.HOME }}/.local/venvs/pipx"

- name: pipx // Install pipx in the virtual environment
  ansible.builtin.pip:
    name: pipx
    executable: "{{ ansible_env.HOME }}/.local/venvs/pipx/bin/pip"

- name: pipx // Add bash config
  ansible.builtin.copy:
    src: bash/pipx.bash
    dest: "{{ ansible_env.HOME }}/.config/bash/pipx.bash"

