- name: starship // Install dependencies
  become: true
  tags: [never, privileged]
  ansible.builtin.package:
    name:
      - curl
    state: present

- name: Starship // Check Install
  shell:
    cmd: starship --version
  register: starship_install_check
  changed_when: false
  ignore_errors: true

- name: Starship // Install
  shell:
    cmd: "curl -sS https://starship.rs/install.sh | sh -s -- --bin-dir '{{ ansible_env.HOME }}/.local/bin' --yes"
  when: starship_install_check.rc != 0

- name: Starship // Clone Config
  ansible.builtin.git:
    repo: "https://github.com/ll-nick/starship-config.git"
    dest: "{{ ansible_env.HOME }}/.config/starship"
    force: "true"

- name: Starship // Add bash config
  ansible.builtin.copy:
    src: bash/prompt.bash
    dest: "{{ ansible_env.HOME }}/.config/bash/prompt.bash"

