- name: Terminator // Install
  become: true
  tags: [never, privileged]
  ansible.builtin.package:
    name: terminator
    state: present

- name: Terminator // Clone Config
  ansible.builtin.git:
    repo: "https://github.com/ll-nick/terminator-config.git"
    dest: "{{ ansible_env.HOME }}/.config/terminator"
    force: "true"

