- name: thefuck // Install
  community.general.pipx:
    name: thefuck

- name: thefuck // Add bash config
  ansible.builtin.copy:
    src: bash/thefuck.bash
    dest: "{{ ansible_env.HOME }}/.config/bash/thefuck.bash"

