- name: Gnome // Ensure Icon Directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.icons"
    state: directory

- name: Gnome // Check Cursor Theme Existence
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.cursor/Catppuccin-Mocha-Blue-Cursors"
  register: cursor_dir

- name: Gnome // Download Icon Theme
  when: not cursor_dir.stat.isdir is defined or not cursor_dir.stat.isdir
  ansible.builtin.unarchive:
    src: https://github.com/catppuccin/cursors/releases/download/v2.0.0/catppuccin-mocha-blue-cursors.zip
    dest: "{{ ansible_env.HOME }}/.icons/"
    remote_src: yes

- name: Gnome // Set Icon Theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/cursor-theme"
    value: "'catppuccin-mocha-blue-cursors'"

- name: Gnome // Download Wallpaper
  ansible.builtin.get_url:
    url: "https://github.com/zhichaoh/catppuccin-wallpapers/blob/main/landscapes/shaded_landscape.png?raw=true"
    dest: "{{ ansible_env.HOME }}/Pictures/wallpaper.png"
    checksum: sha256:1199a43751f1234d3fb92ecf614fbf34de2c07334d3fdd355891044f51bddada

- name: Gnome // Set Wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///{{ ansible_env.HOME }}/Pictures/wallpaper.png'"

