- name: Gnome // Install psutil
  become: true
  tags: [never, privileged]
  ansible.builtin.package:
    name:
      - python3-psutil
    state: present

- name: Gnome // Download Icon Theme
  ansible.builtin.unarchive:
    src: https://github.com/catppuccin/cursors/releases/download/v2.0.0/catppuccin-mocha-blue-cursors.zip
    dest: "{{ ansible_env.HOME }}/.local/share/icons/"
    remote_src: yes
    creates: "{{ ansible_env.HOME }}/.icons/catppuccin-mocha-blue-cursors"

- name: Gnome // Set Icon Theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/cursor-theme"
    value: "'catppuccin-mocha-blue-cursors'"

- name: Gnome // Download Wallpaper
  ansible.builtin.get_url:
    url: "https://github.com/zhichaoh/catppuccin-wallpapers/blob/main/landscapes/shaded_landscape.png?raw=true"
    dest: "{{ ansible_env.HOME }}/Pictures/wallpaper.png"
    checksum: sha256:1199a43751f1234d3fb92ecf614fbf34de2c07334d3fdd355891044f51bddada

- name: Gnome // Set Wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///{{ ansible_env.HOME }}/Pictures/wallpaper.png'"

