- name: Copy mise config
  ansible.builtin.copy:
    src: mise.toml
    dest: "{{ ansible_env.HOME }}/.config/mise/conf.d/uv.toml"

- name: Install
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.local/bin/mise install"
  changed_when: false
