- name: Copy mise config
  ansible.builtin.copy:
    src: mise.toml
    dest: "{{ ansible_env.HOME }}/.config/mise/conf.d/eza.toml"

- name: Install
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.local/bin/mise install"
  changed_when: false

- name: Add bash config
  ansible.builtin.copy:
    src: eza.bash
    dest: "{{ ansible_env.HOME }}/.config/bash/eza.bash"

- name: Add nu config
  ansible.builtin.copy:
    src: eza.nu
    dest: "{{ ansible_env.HOME }}/.config/nushell/autoload/eza.nu"
