- hosts: local
  become: true
  tags: [never, privileged]
  pre_tasks:
    - name: Pre-Run // Update pacman cache
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: Pre-Run // Update apt cache
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Full setup
  hosts: local
  pre_tasks:
    - name: Check if host has a display
      set_fact:
        has_display: >-
          {{
            (ansible_facts['env']['DISPLAY'] is defined
             and ansible_facts['env']['DISPLAY'] is match('^:[0-9]+$'))
            or
            (ansible_facts['env']['WAYLAND_DISPLAY'] is defined
             and ansible_facts['env']['WAYLAND_DISPLAY'] | length > 0)
          }}

  roles:
    - role: bash
    - role: fzf
    - role: lazygit
    - role: leadr
    - role: locale
    - role: neovim
    - role: nodejs
    - role: pipx
    - role: starship
    - role: thefuck
    - role: tmux
    - role: update
    - role: z

    - role: gnome
      when: has_display
    - role: keyboard
      when: has_display
    - role: kitty
      when: has_display
    - role: nerdfont
      when: has_display
    - role: xdg-directories
      when: has_display

    - role: mrt
      when: "'mrt' in ansible_hostname"
