- name: Install Debian dependencies
  become: true
  tags: [never, privileged]
  ansible.builtin.package:
    name:
      - unzip # clangd
    state: present

- name: Get glibc version
  command: ldd --version
  register: ldd_output
  changed_when: false

- name: Parse glibc version from ldd output
  set_fact:
    glibc_version: "{{ ldd_output.stdout_lines[0].split()[-1] }}"

- name: Install for newer glibc versions
  ansible.builtin.shell: |
    {{ ansible_env.HOME }}/.local/bin/mise use --global --pin neovim@{{ nvim_version }}
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/mise/installs/nvim"
  when: glibc_version is version('2.32', '>=')

- name: Install for older glibc versions
  ansible.builtin.unarchive:
    src: "https://github.com/neovim/neovim-releases/releases/download/{{ nvim_version }}/nvim-linux-x86_64.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/"
    remote_src: yes
    extra_opts: ['--strip-components=1']
  when: glibc_version is version('2.32', '<')

- name: Clone Config
  ansible.builtin.git:
    repo: "{{ github_prefix }}ll-nick/neovim-config.git"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    force: "true"

- name: Add bash config
  ansible.builtin.copy:
    src: nvim.bash
    dest: "{{ ansible_env.HOME }}/.config/bash/nvim.bash"

