- name: Install
  ansible.builtin.shell: |
    {{ ansible_env.HOME }}/.local/bin/mise use --global bat
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/mise/installs/bat"

- name: Ensure config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/bat/themes"
    state: directory

- name: Add dark theme
  ansible.builtin.copy:
    src: "Catppuccin Mocha.tmTheme"
    dest: "{{ ansible_env.HOME }}/.config/bat/themes/Catppuccin Mocha.tmTheme"

- name: Add light theme
  ansible.builtin.copy:
    src: "Catppuccin Latte.tmTheme"
    dest: "{{ ansible_env.HOME }}/.config/bat/themes/Catppuccin Latte.tmTheme"

- name: Add config
  ansible.builtin.copy:
    src: config
    dest: "{{ ansible_env.HOME }}/.config/bat/config"

- name: Add bash config
  ansible.builtin.copy:
    src: bat.bash
    dest: "{{ ansible_env.HOME }}/.config/bash/bat.bash"

- name: Add nushell config
  ansible.builtin.copy:
    src: bat.nu
    dest: "{{ ansible_env.HOME }}/.config/nushell/autoload/bat.nu"

